name: mbitschool
favicon: null
layout_spectrum: 0.3108941656537354
typography_spectrum: 0.47735759313218296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bdbdbd'
    - '#fafafa'
    - '#7d7d7d'
    - '#252525'
    - '#cc0001'
  brandStrength: 0.8134365037549287
  lightness: 0.2884020621422678
  saturation: 0.91555963200517
  rhythmicContrast: 0.5875763213261962
purpose: []
