name: mbit school
favicon: null
layout_spectrum: 0.74236
typography_spectrum: 0.25447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b42526'
    - '#000000'
    - '#9f9f9f'
    - '#373737'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5875763213261962
purpose: []
