name: mbit school
favicon: null
layout_spectrum: 0.24444
typography_spectrum: 0.40183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b42526'
    - '#000000'
    - '#9f9f9f'
    - '#373737'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
